# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuiti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=240)),
                ('date_tuiti', models.DateTimeField(auto_now_add=True)),
                ('multimedia', models.ImageField(blank=True, null=True, upload_to=b'media/tuit_pics')),
                ('total_likes', models.IntegerField(default=0)),
                ('total_retuits', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
