# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_userfollowsuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowsuser',
            old_name='user_1',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='userfollowsuser',
            old_name='user_2',
            new_name='follower',
        ),
    ]
